config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :articles, only: [:index, :create, :new, :show] do
    collection do
      get :nodes_graph_data
      get :dots_chart
      get :dots_chart_data
    end
  end

  post 'search',      to: 'search#search'
  get 'autocomplete', to: 'search#autocomplete'

  root to: 'articles#index'

  mount Dashboard::Engine, at: "/dashboard", :as => "dashboard_engine"
end

app/models/article.rb
require 'elasticsearch/model'

class Article < ActiveRecord::Base
  include Searchable

  mount_uploader :image, ImageUploader
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    searchkick match: :word_start, searchable: [:title, :content], autocomplete: ['title']

    def search_data
      {
        title: title,
        content: content
      }
    end

    def self.custom_search(options)
      self.search(options[:query], misspellings: { below: 5 })
    end

    Article.reindex
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def dots_chart
  end

  def dots_chart_data
    render json: [{
                    data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
                  }, {
                    data: [39.9, 31.5, 96.4, 29.2, 94.0, 176.0, 135.6, 198.5, 216.4, 94.1, 195.6, 4.4]
                  }]
  end

  def nodes_graph_data
    json_data = { links: [
                    { source: 1, target: 0, weight: rand(0..1.0) },
                    { source: 0, target: 2, weight: rand(0..1.0) },
                    { source: 3, target: 0, weight: rand(0..1.0) },
                    { source: 3, target: 1, weight: rand(0..1.0) }
                  ],
                  nodes: [
                    { label: "node 0", group: 1 },
                    { label: "node 1", group: 1 },
                    { label: "node 2", group: 2 },
                    { label: "node 3", group: 2 }
                  ],
                  labelAnchorLinks: [
                    { source: 0, target: 1, weight: 1 },
                    { source: 2, target: 3, weight: 1 },
                    { source: 4, target: 5, weight: 1 },
                    { source: 6, target: 7, weight: 1 }
                  ]
                }

    render json: json_data
  end

  private

  def article_params
    params.require(:article).permit :title, :content, :image
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  respond_to :js, only: [:search]

  def search
    @articles = params[:q].presence ? Article.custom_search(query: params[:q]) : Article.all

    render 'components/search'
  end

  def autocomplete
    results = Article.search(params[:q], fields:[:title], limit: 10)

    render json: results.empty? ? "No item was found" : results.map(&:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles_list.html.haml
#articles-container-data
  - @articles.each do |article|
    - image_content = article.image? ? article.image_url(:thumb) : 'sample_overlay'
    .col-xs-6.col-md-4.box.panel.panel-default
      - if article.id == 1
        %svg#graph
      - else
        = link_to (image_tag image_content, size: '95'), article_path(article)
      .panel-body
        %h2= link_to article.title, article
        %span= link_to article.content, article

app/views/articles/_form.html.haml
= form_for @article, html: { class: "form form-horizontal article" } do |f|
  .form-group
    = f.label :title, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, class: 'form-control', required: true
    = f.error_span(:title)
  .form-group
    = f.label :image, class: 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :image, class: 'form-control', required: false
  .form-group
    = f.label :content, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :content, class: 'form-control', required: true
    = f.error_span(:content)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), articles_path, :class => 'btn btn-default'

app/views/articles/dots_chart.html.haml
:javascript
  $(function() {
      //Initialize filterizr with default options
      $('.filtr-container').filterizr();
  });


#container
  %span= "Chart Types"
  = select_tag 'chart_type', options_for_select(['--Select Chart Type--', 'spline', 'line'])

app/views/articles/edit.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/index.html.haml
- model_class = Article
.page-header
  %h1= t '.title', default: model_class.model_name.human.pluralize.titleize
  = link_to t('.new', default: t("helpers.links.new")), new_article_path, class: 'btn btn-primary'
  = link_to 'All Articles', articles_path if params[:q]

.container-fluid#articles-container
  .row
    = render 'articles_list'

app/views/articles/new.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/show.html.haml
- model_class = Article
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @article.title
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @article.content


= link_to t('.back', :default => t("helpers.links.back")), articles_path, :class => 'btn btn-default'

= link_to t('.destroy', :default => t("helpers.links.destroy")), article_path(@article), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Blog
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js"
  = javascript_include_tag "http://d3js.org/d3.v3.min.js"
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Blog", main_app.root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Article", new_article_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - # Search
        = render 'components/search'
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield